mysql:
  host: 127.0.0.1
  port: 3306
  database: blog
  username: admin
  password: password

pg:
  host: 127.0.0.1
  port: 5432
  database: blog
  username: admin
  password: password

sqlite:
  database: config/test.db

