mysql:
  host: "${MYSQL_HOST}"
  port: "${MYSQL_PORT}"
  database: "${MYSQL_DATA}"
  username: "${MYSQL_USER}"
  password: "${MYSQL_PASS}"

pg:
  database: "${PG_URL}"

# sqlite:
#   database: config/test.db

